# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# 2020年11月30日16:53:51 https://github.com/ddgksf2013/TaskAction/blob/master/youth/Task/youth.js

name: 京东宠汪汪偷好友狗粮和积分
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4,22 * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【京东宠汪汪偷好友狗粮和积分】'
        run: |
          node ./jd_joy_steal.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          jdJoyStealCoin: ${{ secrets.jdJoyStealCoin }}
          JOY_HELP_FEED: ${{ secrets.JOY_HELP_FEED }}
